name: dess
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gradient_borders: ^1.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  simple_gradient_text: ^1.3.0
  flutter_localization: ^0.2.0
  flutter_i18n: ^0.36.0
  dio: ^5.5.0+1
  http: ^1.2.2
  shared_preferences: ^2.3.0
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logodes.png
    - assets/images/deslogo.png
    - assets/images/desname.png
    - assets/images/desInitial.png
    - assets/images/line.png
    - assets/images/googlevetor.png
    - assets/images/facebookvetor.png
    - assets/images/ENNTRE.png
    - assets/images/formvetor1.png
    - assets/images/formvetor2.png
    - assets/images/formvetor3.png
    - assets/images/vetorfla.png
    - assets/images/sub9vetor.png
    - assets/images/sub11vetor.png
    - assets/images/sub10vetor.png
    - assets/images/sub13vetor.png
    - assets/images/gestvetor.png
    - assets/images/appbarvetor.png
    - assets/images/logout.png
    - assets/images/vetortecnic.png
    - assets/images/vetortatic.png
    - assets/images/vetorfisic.png
    - assets/images/neurology.png
    - assets/images/sprint.png
    - assets/images/exercise.png
    - assets/images/editorgradient.svg
    - assets/images/event.svg
    - assets/images/health.svg
    - assets/images/cash.svg
    - assets/images/gradientline.png
    - assets/images/sportvetor.svg
    - assets/images/passvetor.svg
    - assets/images/managevetor.svg
    - assets/images/homevetor.svg
    - assets/images/vertline.png
    - assets/images/background.svg
    - assets/images/background1.svg
    - assets/images/background2.svg
    - assets/images/staron.svg
    - assets/images/staroff.svg
    - assets/images/mood_bad.svg
    - assets/images/cardvetor.svg
    - assets/images/bordervetor.svg
    - assets/images/flamengo.svg
    - assets/images/gleydon.svg
    - assets/images/dias.svg
    - assets/images/humilha.svg
    - assets/images/manel1.svg
    - assets/images/manel2.svg

  fonts:
    - family: STRETCH
      fonts:
        - asset: fonts/stretch.otf
          style: italic
    - family: OUTFIT
      fonts:
        - asset: fonts/outfit.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logodes.png" 
